runtime: python27
api_version: 1
threadsafe: yes
service: planning-poker

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: pytz
  version: "2017.3"

handlers:

# Resources
- url: /css
  static_dir: static/dist/css
- url: /html
  static_dir: static/dist/html
- url: /images
  static_dir: static/dist/images
- url: /js
  static_dir: static/dist/js

- url: .*
  script: main.app
  secure: always

# The following directories/files will be ignored by GAE when deploying
skip_files:
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.pyc$
- ^(.*/)?\..*$
- ^(.*/)gulpfile.js
- ^(.*/)package.json
- ^(.*/)yarn.lock
- ^(.*/)?.*/gulp/.*$
- ^(.*/)?.*/node_modules/.*$
