runtime: python27
api_version: 1
threadsafe: yes
service: planning-poker

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: pytz
  version: "2017.3"

handlers:

# Resources
- url: /planning-poker/static/(.*\.js)
  expiration: "365d"
  mime_type: application/javascript
  secure: always
  static_files: dist/\1
  upload: dist/(.*\.js)

- url: /planning-poker/static/(.*\.js\.map)
  expiration: "365d"
  mime_type: application/json
  secure: always
  static_files: dist/\1
  upload: dist/(.*\.js\.map)

- url: .*
  script: main.app
  secure: always

# The following directories/files will be ignored by GAE when deploying
skip_files:
- ^(.*/)?.*/gulp/.*$
- ^(.*/)?.*/node_modules/.*$
- ^(.*/)?.*/src/.*$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.pyc$
- ^(.*/)?\..*$

- ^(gulp/.*)
- ^(node_modules/.*)
- ^(src/.*)

- angular.json
- gulpfile.js
- package.json
- tsconfig.json
- yarn.lock
